2025-08-24 16:03:53 - root - ERROR - Ошибка инициализации: expected 'except' or 'finally' block (config_manager.py, line 104)
